version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    image: php:8.2-fpm
    container_name: hris_app
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    networks:
      - laravel

    depends_on:
      - mysql
      - redis

    extra_hosts:
      - "host.docker.internal:host-gateway"

  webserver:
    image: nginx:alpine
    container_name: hris_web
    restart: unless-stopped
    ports:
      - "8090:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  mysql:
    image: mysql:8.3
    container_name: hris_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hrisdb
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - laravel

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: hris_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8099:80"
    networks:
      - laravel

  redis:
    image: redis:alpine
    container_name: hris_redis
    ports:
      - "6379:6379"
    networks:
      - laravel

volumes:
  mysql_data:

networks:
  laravel:
    driver: bridge
